name: perfumei
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.3.1                         #Controla o tema do aplicativo
  lottie: ^3.0.0                                    #Animações
  wakelock_plus: ^1.1.4                             #Para manter a Tela ligada
  cached_network_image: ^3.3.1                      #Cache de imagens
  google_fonts: ^6.1.0
  bloc: ^8.1.1                                      #Controle de estado
  flutter_bloc: ^8.1.2                              #Controle de estado
  font_awesome_flutter: ^10.6.0
  image: ^4.1.4                                     #Para processar a imagem
  html: ^0.15.1                                     #Para processar html
  animations: ^2.0.11                               #Animações
  dio: ^5.4.0                                       #Classe para controle de requisições
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_objectbox_store: ^1.1.3
  objectbox: ^2.4.0                                 #Armazenamento de dados
  objectbox_flutter_libs: ^2.4.0                    #Armazenamento de dados
  uuid: ^4.3.3
  path_provider: ^2.1.2
  rflutter_alert: ^2.0.7
  dart_ddi: 
    path: '../'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: "^0.13.1"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_native_splash:
  image: "assets/splash.jpg"
  color: "#d2eaf7"
  color_dark: "#002940"
  android: true
  ios: true
  web: false
  android_gravity: "fill"
  android_12:
    image: "assets/splash.jpg"
    icon_background_color: "#d2eaf7"
    icon_background_color_dark: "#002940"

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/

 
