name: dart_ddi
description: "A Dependency Injection package, with Qualifier, Decorators, Interceptors and more. Inspired by Java CDI."
version: 0.12.0
homepage: https://github.com/Willian199/dart_ddi
repository: https://github.com/Willian199/dart_ddi
documentation: https://github.com/Willian199/dart_ddi/blob/master/README.md
issue_tracker: https://github.com/Willian199/dart_ddi/issues
tags:
  - dependency
  - package
  - inject
  - management

topics:
  - dependency
  - dependency-injection
  - dependency-injector
  - dependency-management
  - cdi

environment:
  sdk: ">=3.4.0 <4.0.0"

dev_dependencies:
  test: ">=1.25.8 <2.0.0"
  lints: ^6.0.0
